services:
  web:
    container_name: zefe_web
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    expose:
      - "8000"
    depends_on:
      - db
      - nginx

  db:
    container_name: zefe_db
    image: postgres:13-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env # Should contain POSTGRES_DB, POSTGRES_USER, POSTGRES_PASSWORD

  nginx:
    container_name: zefe_nginx
    restart: always
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - web

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./letsencrypt:/var/lib/letsencrypt
    entrypoint: /bin/sh -c
    command: >
      "trap exit TERM; while :; do sleep 12h & wait $${!}; certbot renew; done"

volumes:
  db_data:
  static_volume:
  media_volume:
