# Generated by Django 5.2.4 on 2025-07-14 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChainEcosystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('SOLANA', 'Solana'), ('ETHEREUM', 'Ethereum'), ('POLKADOT', 'Polkadot'), ('BITCOIN', 'Bitcoin'), ('AVALANCHE', 'Avalanche'), ('POLYGON', 'Polygon')], max_length=50, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='linkedin',
            new_name='linkedin_url',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='twitter',
            new_name='twitter_username',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='telegram',
        ),
        migrations.AddField(
            model_name='user',
            name='is_onboarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='position',
            field=models.CharField(blank=True, choices=[('CO_FOUNDER', 'Co-founder'), ('DEVELOPER', 'Developer'), ('DESIGNER', 'Designer'), ('MARKETER', 'Marketer')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='project_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='superteam_chapter',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='verticals',
            field=models.ManyToManyField(blank=True, to='user.vertical'),
        ),
        migrations.AlterField(
            model_name='vertical',
            name='name',
            field=models.CharField(choices=[('DeFi', 'DeFi'), ('NFT', 'NFT'), ('Gaming', 'Gaming'), ('Infra', 'Infra'), ('Social', 'Social'), ('Tokenization', 'Tokenization')], max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='chain_ecosystems',
            field=models.ManyToManyField(blank=True, to='user.chainecosystem'),
        ),
    ]
