# Generated by Django 5.2.4 on 2025-07-17 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_connectionrequest_userspamscore_connection_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connectionrequest',
            old_name='message',
            new_name='note_content',
        ),
    ]
