# Generated by Django 5.2.4 on 2025-07-18 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_collaborationpost_comment_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='user.comment'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('MENTION', 'Mention in Comment'), ('CONNECTION_ACCEPTED', 'Connection Request Accepted'), ('CONNECTION_REQUEST', 'New Connection Request'), ('POST_COMMENT', 'New Comment on Post'), ('COMMENT_REPLY', 'Reply to Comment')], max_length=20),
        ),
    ]
