# Generated by Django 5.2.4 on 2025-08-02 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_remove_userprofile_email_alter_chainecosystem_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='linkedin_url',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
