# Generated by Django 5.2.4 on 2025-08-03 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_userprofile_linkedin_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='message',
        ),
    ]
